apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mlflow-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  tls:
  - hosts:
      - mlflow.labs.itmo.loc
    secretName: mlflow-tls

  rules:
  - host: mlflow.labs.itmo.loc
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mlflow-external
            port:
              number: 5000
