apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    # редирект с HTTP на HTTPS
    server {
        listen 80;
        server_name mlflow.labs.itmo.loc;
        return 301 https://$host$request_uri;
    }

    # основной HTTPS сервер
    server {
        listen 443 ssl;
        server_name mlflow.labs.itmo.loc;

        ssl_certificate /etc/nginx/ssl/tls.crt;
        ssl_certificate_key /etc/nginx/ssl/tls.key;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;

        location / {
            proxy_pass http://10.114.0.4:5000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
        }
    }